name: lol_pedia
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.2+2

environment:
  sdk: '>=3.0.0-204.0.dev <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  flutter_bloc: ^8.1.2
  # admob_flutter: ^3.0.0
  get_it: ^7.2.0
  injectable: ^2.1.0
  animated_text_kit: ^4.2.2
  meta: ^1.9.0
  build_runner: ^2.4.0
  bloc: ^8.1.1
  bloc_concurrency: ^0.2.1
  equatable: ^2.0.5
  shared_preferences: ^2.0.18
  cached_network_image: ^3.2.3
  responsive_grid_list: ^1.3.1
  carousel_images: ^1.1.2
  google_fonts: ^4.0.3
  flutter_launcher_icons: ^0.12.0
  rename: ^2.1.1
  animations: ^2.0.7
  flutter_staggered_animations: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  bloc_test: ^9.1.0
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0
  injectable_generator: ^2.1.3
flutter:
  uses-material-design: true
  fonts:
    - family: super_punch
      fonts:
        - asset: ./resources/fonts/SUPER PUNCH.ttf
    - family: kenyan_coffee
      fonts:
        - asset: ./resources/fonts/kenyan coffee rg.otf
flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_logo.png"