name: lol_pedia
description: A new Flutter project.
publish_to: "none"
version: 2.0.26+23

environment:
  sdk: ">=3.0.0-204.0.dev <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.1.0
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  injectable: ^2.3.2
  animated_text_kit: ^4.2.2
  meta: ^1.15.0
  build_runner: ^2.4.6
  bloc: ^8.1.2
  bloc_concurrency: ^0.2.2
  equatable: ^2.0.5
  shared_preferences: ^2.2.1
  responsive_grid_list: ^1.4.0
  carousel_images: ^1.1.2
  google_fonts: ^6.1.0
  flutter_launcher_icons: ^0.13.1
  rename: ^3.0.0
  animations: ^2.0.8
  flutter_staggered_animations: ^1.1.1
  intl: ^0.19.0
  scrollable_positioned_list: ^0.3.8
  flutter_local_notifications: ^17.0.0
  permission_handler: ^11.0.1
  cached_network_image: ^3.3.0
  url_launcher: ^6.1.14
  font_awesome_flutter: ^10.5.0
  path_provider: ^2.1.1
  basic_utils: ^5.6.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  bloc_test: ^9.1.4
  mocktail: ^1.0.1
  very_good_analysis: ^5.1.0
  injectable_generator: ^2.4.1
flutter:
  uses-material-design: true
  fonts:
    - family: super_punch
      fonts:
        - asset: ./resources/fonts/SUPER PUNCH.ttf
    - family: kenyan_coffee
      fonts:
        - asset: ./resources/fonts/kenyan coffee rg.otf
  assets:
    - assets/img/dragons/ocean.png
    - assets/img/dragons/cloud.png
    - assets/img/dragons/infernal.png
    - assets/img/dragons/mountain.png
    - assets/img/dragons/chemtech.png
    - assets/img/dragons/hextech.png
    - assets/img/dragons/elder.png

    - assets/img/stats/ability_power.png
    - assets/img/stats/armor.png
    - assets/img/stats/armor_pen.png
    - assets/img/stats/attack_damage.png
    - assets/img/stats/attack_speed.png
    - assets/img/stats/cdr_reduction.png
    - assets/img/stats/critical_chance.png
    - assets/img/stats/health.png
    - assets/img/stats/health_regen.png
    - assets/img/stats/mana.png
    - assets/img/stats/mana_regen.png
    - assets/img/stats/life_steal.png
    - assets/img/stats/magic_pen.png
    - assets/img/stats/magic_resist.png
    - assets/img/stats/move_speed.png
    - assets/img/stats/omnivamp.png
    - assets/img/stats/range.png
    - assets/img/stats/tenacity.png

    - assets/img/misc/gold.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_logo.png"
